apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kitium-docker.fullname" . }}-web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "kitium-docker.name" . }}
      tier: web
  template:
    metadata:
      labels:
        app: {{ include "kitium-docker.name" . }}
        tier: web
    spec:
      containers:
        - name: web
          image: {{ .Values.image.registry }}/web:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NODE_ENV
              value: production
            - name: NEXT_PUBLIC_API_URL
              value: {{ .Values.env.nextPublicApiUrl }}
          ports:
            - containerPort: 3001
          readinessProbe:
            httpGet:
              path: /
              port: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kitium-docker.fullname" . }}-web
spec:
  selector:
    app: {{ include "kitium-docker.name" . }}
    tier: web
  ports:
    - port: 80
      targetPort: 3001
