apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kitium-docker.fullname" . }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "kitium-docker.name" . }}
      tier: redis
  template:
    metadata:
      labels:
        app: {{ include "kitium-docker.name" . }}
        tier: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          args: ["--requirepass", {{ .Values.env.redisPassword | quote }}, "--appendonly", "yes"]
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: {{ include "kitium-docker.name" . }}
    tier: redis
  ports:
    - port: 6379
